-- MySQL Script generated by MySQL Workbench
-- Sun 11 Mar 2018 02:23:36 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema writit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema writit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `writit` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `writit` ;

-- -----------------------------------------------------
-- Table `writit`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `writit`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `writit`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `writit`.`comments` (
  `id_comments` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `id_user` INT NULL,
  `id_post` INT NULL,
  PRIMARY KEY (`id_comments`),
  INDEX `post` (`id_post` ASC),
  INDEX `fk_comments_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_comments_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `writit`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `writit`.`votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `writit`.`votes` (
  `id_votes` INT NOT NULL,
  `vote` VARCHAR(10) NULL,
  `id_user` INT NULL,
  `post_id` INT NULL,
  PRIMARY KEY (`id_votes`),
  INDEX `fk_votes_user_idx` (`id_user` ASC),
  INDEX `post` (`post_id` ASC),
  CONSTRAINT `fk_votes_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `writit`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votes_post`
    FOREIGN KEY ()
    REFERENCES `writit`.`post` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `writit`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `writit`.`post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `body` TEXT NULL,
  `imag` VARCHAR(45) NULL,
  `video` VARCHAR(45) NULL,
  `rateing` INT NULL,
  `votes` INT NULL,
  `comment_id` INT NULL,
  `image` VARCHAR(45) NULL,
  `video` VARCHAR(45) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `comments` (),
  INDEX `fk_post_1_idx` (`comment_id` ASC),
  INDEX `fk_post_votes_idx` (`votes` ASC),
  INDEX `fk_post_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_post_comment`
    FOREIGN KEY (`comment_id`)
    REFERENCES `writit`.`comments` (`id_post`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_votes`
    FOREIGN KEY (`votes`)
    REFERENCES `writit`.`votes` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `writit`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
